suit:
  default:
    - category: lapel
      description: "Notch lapels are the most widely used lapels and are a safe and stylish choice for any suit. Peak lapels add a little pizazz for those who want to stand out. TR tip: If you are unsure, go with the notch lapel, you don't necessarily want anything to distract from the perfect fit of your tailored suit."
      options:
        notch:
         default: true
         image: customizations/suits/lapel-notch.png
        peak:
          default: false
          image: customizations/suits/lapel-peak.png
        narrow:
          default: false
          image: customizations/suits/lapel-narrow.png
    - category: buttons
      description: "The modern standard and a fashionable choice is the two button suit. Two button suits fit more of a classic style and look great on taller guys. A one button suit is a very stylish option for those who want to be adventurous. TR tip: If you are going to add a vest, stick with the two button jacket."
      options:
        1:
          default: false
          image: customizations/suits/buttons-one.png
        2:
          default: true
          image: customizations/suits/buttons-two.png
        3:
          default: false
          image: customizations/suits/buttons-three.png
    - category: vents
      description: "Having two vents is the traditional, safe and stylish choice. One vent is a way to make your suit modern and sleek without distracting from the excellent fit (we love the single vent). TR tip: If you are a shorter guy, go ahead and get the double vent, the vertical vents help to draw the eye upward and elongate the body."
      options:
        0:
          default: false
          image: customizations/suits/vents-none.png
        1:
          default: false
          image: customizations/suits/vents-one.png
        2:
          default: true
          image: customizations/suits/vents-two.png
    - category: pleats
      description: "Pleats are typically associated with old-fashioned suits. If you are looking for a modern, trendier look, we recommend going with no pleats and no cuffs on the pants."
      options:
        0:
          default: true
          image: customizations/suits/pleats-none.png
        1:
          default: false
          image: customizations/suits/pleats-one.png
        2:
          default: false
          image: customizations/suits/pleats-two.png
    - category: pant_cuffs
      description: "Pant cuffs were a suit staple in previous decades, but unless you are going for an older, more classic look, we recommend sticking with no pant cuffs. It keeps the suit lines clean and sharp, keeping those heads on a swivel."
      options:
        false:
          default: true
          image: customizations/suits/cuffs-no.png
        true:
          default: false
          image: customizations/suits/cuffs-yes.png
    - category: fit
      description: "The tailored fit is guaranteed to look great on most guys. A regular fit is great for guys with a fuller figure. And the slim fit is great for lean guys who want a very tight fitting suit and know they will not have any weight changes in the future. TR tip: Regardless of the fit option, our suits are tailored to your measurements, so slim or full-figured, your suit will look and feel great."
      options:
        slim:
          default: false
          image: customizations/suits/fit-slim.png
        tailored:
          default: true
          image: customizations/suits/fit-tailored.png
        normal:
          default: false
          image: customizations/suits/fit-normal.png
    - category: lining
      description: "The most common selection is matching lining, which works with the suit to bring out the fabrics natural intrigue. Contrasting linings are a great choice if you want to add a little flash to your suit, making your suit stand out. TR tip: A unique lining is a great way to make your suit stand out and really separates your suit from the off-the-rack crowd; we recommend being bold."
      no_recommendation: true
      options:
        black:
          default: true
          image: customizations/suits/linings/black.jpg
        gray:
          default: false
          image: customizations/suits/linings/gray.jpg
        navy:
          default: false
          image: customizations/suits/linings/navy.jpg
        black-blue-paisley:
          default: false
          image: customizations/suits/linings/black-blue-paisley.jpg
        black-paisley:
          default: false
          image: customizations/suits/linings/black-paisley.jpg
        cream-paisley:
          default: false
          image: customizations/suits/linings/cream-paisley.jpg
        purple-paisley:
          default: false
          image: customizations/suits/linings/purple-paisley.jpg
    - category: pick_stitching
      description: "Pick stitching really emphasizes the stitching on your suit making it clear that you went with a tailored option. This is a fairly bold look, so we recommend opting out unless you are familiar with the look and know you want it."
      options:
        false:
          default: true
          image: customizations/suits/pick-stitching-no.png
        true:
          default: false
          image: customizations/suits/pick-stitching-yes.png
          label: Yes (+$10)
    - category: vest
      description: "Do you want to make your suit a three-piece? You can add a matching vest to your suit order for $79. A three-piece suit is sure to draw looks and makes a bold statement that you are serious about your style game."
      options:
        0:
          default: true
          image: customizations/suits/vest-no.png
          label: No Vest (+$0)
        3:
          default: false
          image: customizations/suits/vest-three.png
          label: 3 Buttons (+$79)
        4:
          default: false
          image: customizations/suits/vest-four.png
          label: 4 Buttons (+$79)
        5:
          default: false
          image: customizations/suits/vest-five.png
          label: 5 Buttons (+$79)

  tuxedo:
    - category: lapel
      description: "Notch lapels are the most widely used lapels and are a safe and stylish choice for any suit. Peak lapels add a little pizazz for those who want to stand out. TR tip: If you are unsure, go with the notch lapel, you don't necessarily want anything to distract from the perfect fit of your tailored suit."
      options:
        shawl:
          default: true
          image: customizations/suits/lapel-shawl.png
        notch:
         default: false
         image: customizations/suits/lapel-notch.png
        peak:
          default: false
          image: customizations/suits/lapel-peak.png
        narrow:
          default: false
          image: customizations/suits/lapel-narrow.png

  custom-fabric:
    - category: fabric
      description: "For the bold suit connoisseur we have the option to build your own suit; including selecting a unique fabric that is not available in our permanent collection. Start by choosing one of our 100% wool premium fabrics. Hover over a fabric to magnify, and click on it to select."
      custom: true
      fabric: true
      options:
        charcoal-pinstripe:
          id: 10005.202/1
          label: Dark Charcoal w/ Wide Pinstripes
          small_image: customizations/suits/fabrics/charcoal-with-pinstripe-small.jpg
          large_image: customizations/suits/fabrics/charcoal-with-pinstripe-large.jpg
          default: true
        granite-red:
          id: 10005.170/1
          label: Granite w/ Red Crosschecks
          small_image: customizations/suits/fabrics/granite-with-red-small.jpg
          large_image: customizations/suits/fabrics/granite-with-red-large.jpg
          default: false
        powder-blue-pinstripe:
          id: 10005.005/2
          label: Powder Blue w/ Pinstripe
          small_image: customizations/suits/fabrics/powder-blue-pinstripe-small.jpg
          large_image: customizations/suits/fabrics/powder-blue-pinstripe-large.jpg
          default: false
        stone-gray-with-blue:
          id: 10005.170/2
          label: Stone Gray w/ Blue Crosschecks
          small_image: customizations/suits/fabrics/stone-gray-with-blue-small.jpg
          large_image: customizations/suits/fabrics/stone-gray-with-blue-large.jpg
          default: false

shirt:
  default:
    - category: collar
      description: "The standard or straight collars are always a nice, clean TR-approved look. The cutaway collar is a solid option for someone that really wants to emphasize a wide tie knot, such as a Windsor. Button-down collars tend to be slightly more casual and can be a nice choice if you are not wearing the shirt with a suit."
      options:
        standard:
          default: true
          image: customizations/shirts/collar-standard.png
        cutaway:
          default: false
          image: customizations/shirts/collar-cutaway.png
        straight:
          default: false
          image: customizations/shirts/collar-straight.png
        button-down:
          default: false
          image: customizations/shirts/collar-button-down.png
    - category: fit
      description: "A slim fit helps to keep the shirt nice and tight to the body so that it doesn’t pooch out the suit in an unsightly way. If you are a fuller-figure man or are planning on wearing the shirt without a suit, a normal fit will look great."
      options:
        slim:
          default: true
          image: customizations/shirts/fit-slim.png
        normal:
          default: false
          image: customizations/shirts/fit-normal.png
    - category: pocket
      description: "So the argument for pockets is that they are functional, but we say ditch the pocket and give your shirt that clean look. This is especially true if you are rocking a skinny tie; a bulky pocket can really throw off the whole balance of the look."
      options:
        false:
          default: true
          image: customizations/shirts/pocket-no.png
          label: No Pocket
        true:
          default: false
          image: customizations/shirts/pocket-yes.png
          label: Pocket
    - category: monogram
      description: "Shirt monogramming can be up to 3 characters, and is almost exclusively used to sport some initials. The monogram will show up on the sleeve cuff that will poke out the bottom of your suit sleeve. <span class=\"label\">Note: monograms cost an extra $5.</span>"
      custom: true
      monogram: true
      max_length: 3
      extra_cost: 5

